name: Appium C# BrowserStack Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-appium-browserstack:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: '8.0.x'
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Install Appium CLI (not strictly required if only using BrowserStack)
      - name: Install Appium and BrowserStack driver
        run: |
          npm install -g appium
          appium driver install uiautomator2

      # ✅ Run Appium C# Tests on BrowserStack
      - name: Run tests on BrowserStack
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

      # Upload reports
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: "**/TestResults/*.trx"
